In [1]:
# flask
import flask # 웹서버 기능 5000번 포트로 서비스

In [2]:
import matplotlib
import numpy as np
print(np.__version__) # 상위 오브젝트가 가진 속성
def pprint(arr): # ndarray : numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype)) # 요소수, 차원, 배열의 자료형
    print("Array's Data: \n", arr)
arr = [1.0, 2.0, 3.0]
a = np.array([1,2,3]) #ndarray 생성 함수(매개변수: 리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data: 
 [1 2 3]


In [20]:
# 인스턴스 상태
a = np.array([0,1,2,3,4,5,6,7,8,9]) #ndarray
print(id(a)) #python core 주소값 확인
print(a.size) #데이터 개수
print(a.astype(np.float32)) #데이터 타입 변경, numpy는 행 중심, 동질적
print(a.dtype.itemsize*a.size) # 전체 메모리 사이즈(바이트)
# iterator for in range => list
a = np.arange(1000) # => ndarray
a

2542382309664
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [14]:
# ndarray 초기화 함수들
print(np.zeros((3,4))) #0
print(np.ones((2,3,4), dtype=np.int16)) # 1,3차원 면, 행, 열
print(np.full((2,2),7))
print(np.eye(4)) # 대각행렬 identity 행렬연산에서 항등원 +, *,
print(np.empty((4,2))) #

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.26083326e-321]
 [1.10343781e-312 8.70018274e-313]]


In [19]:
a = np.arange(0, 100, 10) # ndarray
indices = [1,5,-1] # 리스트
print(indices)
b = a[indices] # 리스트를 첨자(인덱스)로 사용
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [23]:
a = np.arange(11,36) # 1차원
print(a)
a.shape = (5,5) # 정상 모양을 갖춘 개수 R
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape) # 차수(5,5)
print(a.ndim) # 2차원
print(a.nbytes) # 100바이트 = 25 * 4
print(a.strides) # (20,4) # (dimensions 간의 간격, 앨리먼트간의 간격) 다음 열의 데이터는 몇바이트를 건너뛰어야 하는가
                 # 다음 행은 몇 바이트를 건너뛰어야 하는가
'''strides는 '걸음걸이'라는 뜻을 가지고 있는 단어이다.
numpy에서는, 각 dimensions를 건너가는데 몇 bytes나 뛰어넘어야 하는지에 대한 정보이다.
예를들어 [[1,2,3],[4,5,6]] 이라는 2차원의 array가 있다.
strides를 사용하면 (dimensions 간의 간격, 앨리먼트간의 간격) 으로 결과가 출력된다.
각 dimensions 간의 간격은 [1,2,3] 의 용량과 같으므로 4바이트인 int32형 3개 = 12 bytes인 것.
그래서 (12,4)로 표현한다. 
strides() = Tuple of bytes to step in each dimension when traversing an array.'''

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [24]:
arr = np.arange(10) # 0,
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) # 마지막 불포함
arr[5:8] = 12 # 데이터 업데이트. 5~8까지 12를 대입하라
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [120]:
# numpy 첨자 생략 불가 [,4]
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d.ndim) # 2차원
print(arr2d[0]) # 행 우선
print(arr2d[0][2]) # 0의 2열
print(arr2d[0,2]) # 바로 위 print(arr2d[0][2])와 같음 ########## 이게 헷갈리네
print()
print(arr2d[:2]) # 0,1행
print(arr2d[:2,1:]) # 끝까지
# print(arr2d[,1:]) R 처럼 행 생략 안됨
print()
print(arr2d[:,1:]) # 모든 각 행의 두번째부터 끝까지
print(arr2d[1, :2]) # [4 5]
print(arr2d[2, :1])
print()
arr2d[:2, :1] = 0
arr2d[:2, :1] = 0
print(arr2d)

2
[1 2 3]
3
3

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]

[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]

[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [122]:
# 실제 저장은 일렬로, 사람이 데이터를 다루는 것은 입체로 - 480바이트
# 행렬 연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야 행렬곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨

print("스트라이드의 값", np.ones((3,4,5), dtype = np.float64).strides) # 3, 4, 5(단일데이터)
# 단일 데이터 float64: 8바이트

스트라이드의 값 (160, 40, 8)


In [33]:
# 문제
arr3d = np.array([ [ [1,2,3],[4,5,6] ],[ [7,8,9],[10,11,12] ] ]) # 2면, 2행 ,3열
print("첫 면", arr3d[0]) #0번 면
print("첫면 첫 행은 =", arr3d[0][0])
print("첫면 첫행, 첫요소는 =", arr3d[0][0][0]) # [면][행][요소]
# 8을 출력하라
print(arr3d[1][0][1])
# 12를 출력하라
print(arr3d[1][1][2])

첫 면 [[1 2 3]
 [4 5 6]]
첫면 첫 행은 = [1 2 3]
첫면 첫행, 첫요소는 = 1
8
12


In [123]:
# 백업이 안됨: 대입하면 같은 주소를 가리키기 때문에 
old_values = arr3d.copy() # 대입: 주소를 복사
arr3d[0] = 42
print("값의 변경 후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [130]:
Z = np.arange(36)
print(Z)
print(Z.ndim, '차원')
print()
Z = Z.reshape((6,6))
print(Z)
print(Z.ndim, '차원')
print()
reshape2 = Z.reshape((2,3,6)) # 면,행,렬
print(reshape2)
print(reshape2.ndim, "차원")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
1 차원

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
2 차원

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
3 차원


In [131]:
arr = np.arange(32).reshape((8,4)) # shape vs. reshape(바꿀 때만)
print(arr)
print(arr[[1,5,7,2]]) # 행 중심
print(arr[[-1,-5,-7,-2]])# 거꾸로 인덱싱
print(arr[[1,5,7,2],[0,3,1,2]]) # 1번행의 5번열, 5번행의 4번열...
print()
# fancy 인덱싱
print(arr[[1,2,5,7]][:, [0,1,2,3]])
print(arr[[1,5,7,2]][:, [0,3,1,2]]) ###########################################################

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [5]:
# 그림 참조 
arr = []
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i*10 + j)
    arr.append(ad)
print(arr)
arr = np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [6]:
# Q1
print(arr)
print("주황색", arr[[0,1,2,3,4],[1,2,3,4,5]])
print("빨간색", arr[[0,2,5],2])
print("하늘색", arr[3:6][:, [0,2,5]])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
주황색 [ 1 12 23 34 45]
빨간색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [60]:
# Q2
#print("빨간색", arr[[0:6], 2]) 이렇게 하면 왜 안돼??????????????????????????????
print("빨간색", arr[:, 2])
print("주황색", arr[0,[3,4]])
print("녹색", arr[[2,4]][:,[0,2,4]])

빨간색 [ 2 12 22 32 42 52]
주황색 [3 4]
녹색 [[20 22 24]
 [40 42 44]]


In [134]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # 4x3
v = np.array([1,0,1])
print("타일 출력")
vv = np.tile(v, (4,1))
print(vv)
y = x + vv # 4x3 배열 연산 => 요소별 연산
print(y)
# 배열 연산: 양쪽 차원이 일치해야 함
print("배열 연산\n", x + v) # 4x3, 4x1 broadcasting
x+3 # 모든 요소에 3을 더함

타일 출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
배열 연산
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [7]:
x = np.arange(6).reshape((3,2))
print(x)
# 거듭제곱(행열곱, @)
# x@x # 앞의 행렬 열수와 뒤의 행렬 행수가 일치해야함 => (3x2)(3x2)라서 안됨. 
# 전치행렬 => .T 또는 transpose()함수 사용을 해야한다.
print(x.T) # x의 전치행렬
print(np.transpose(x))

print(x@x.T) # 거듭제곱(행열곱)의 결과는 3x3
# https://ko.wikipedia.org/wiki/%EC%A0%84%EC%B9%98%ED%96%89%EB%A0%AC

[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
[[0 2 4]
 [1 3 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]


In [141]:
arr= np.arange(24).reshape((2,3,4)) # 2면 3행 4열
print("arr = \n", arr)
print("arr.transpose((1,0,2)) = \n", arr.transpose((1,0,2))) # 2면 3행 4열 -> 3면 2행 4열
print("arr.transpose((0,1,2)) = \n", arr.transpose((0,1,2)))

arr = 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
arr.transpose((1,0,2)) = 
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
arr.transpose((0,1,2)) = 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [142]:
names = np.array(['GMP', 'PUS', 'CJJ', 'gMP', 'cJJ', 'PUS', 'PUS'])
data = np.random.randn(7,4) # 7x4
print(data)
print(names == 'GMP') # 1,0,0,0,0,0,0
print(data[names=='GMP']) # 0번행
print(data[names=='GMP', 2:])
print(data[names=='GMP', 3])
print(names != 'GMP') # 0,1,1,1,1,1,1

print()
print(~(names != 'GMP')) # '~' = 부정
mask = (names == 'GMP') | (names =='cJJ')
print(mask)
print(data[mask])

[[-1.55599459  1.03615081  0.19889181  0.09477533]
 [-1.52673203  2.47463214  1.08269769 -0.89127185]
 [ 0.28711708 -1.88898259 -0.35001688  1.11346897]
 [-0.52816053 -0.86610379 -0.10961215  0.63445069]
 [ 0.16038509  0.45966734 -0.92535261 -0.64343556]
 [ 1.23693374  1.14498558  0.02166777 -0.69389212]
 [-1.10243052  0.08928026  0.43659355  1.68735757]]
[ True False False False False False False]
[[-1.55599459  1.03615081  0.19889181  0.09477533]]
[[0.19889181 0.09477533]]
[0.09477533]
[False  True  True  True  True  True  True]

[ True False False False False False False]
[ True False False False  True False False]
[[-1.55599459  1.03615081  0.19889181  0.09477533]
 [ 0.16038509  0.45966734 -0.92535261 -0.64343556]]


In [86]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond)) # 요소별로 데이터 묶음, zip 고유 포맷
print(list(zip(xarr, yarr, cond))) 
result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)] # 3 항연산자
print("result = ", result) 

result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[ 0.38212189  0.47476044  0.21108633 -2.28825117]
 [-1.25076867  1.44438278  0.21692185 -0.73415977]
 [-0.46451538  1.68349117  1.2676929   0.59630665]
 [ 1.00264539  0.20809645 -1.28845367  1.1387486 ]]
[[ 2  2  2 -2]
 [-2  2  2 -2]
 [-2  2  2  2]
 [ 2  2 -2  2]]


In [91]:
# 문제) 다음 데이터를 이용하여 두개다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일때는 2, 그 외일때는 3으로 처리하여 출력해라
# 0,1,2,3
# 조건문 4개 써라
# where을 쓰면 3개 쓰게 된다
result = []
cond1 = np.array([1,0,1,1,0,0,1], dtype = bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype = bool)

In [92]:
for i in range(len(cond1)):
    if (cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print("조건문", result)
result = np.where(cond1 & cond2, 0, np.where(cond1, 1,
                                            np.where(cond2, 2, 3))) ####################################################
print("제3항연산자", result)
result = 1*(cond1 & ~cond2) + 2*(cond2 & ~cond1) + 3* ~(cond1 | cond2)
print("수식을 이용한", result)

조건문 [1, 2, 0, 0, 3, 2, 0]
제3항연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [95]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
z = np.zeros_like(x) # 다른 행렬과 같은 사이즈의 초기화 (초기값을 모두 0으로)
for i in range(10000):
    z[i] = x[i] + y[i]

In [97]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a==b)) # 전체가 참일 때 참
print(np.any(a==b)) # 하나라도 참이면 참
print(np.exp(a)) # 지수함수(자연대수: 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [101]:
# 선형대수: 선형으로 해결하자. => 비선형도 잘게 나누면 선형

In [ ]:
# 행렬의 종류
# - 정방행렬: 정사각형 (행과 열수가 같은 행렬)
# - 대칭행렬: 전치행렬이 스스로와 같은 행렬
# - 대각행렬: 주대각선을 제외한 곳의 원소가 0인 정사각행렬 (scale을 변화시키는 요소)
# - 단위행렬(identity): 행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬. 왼쪽에서 오른쪽 대각선 아래로 성분이 1, 나머지가 0
# - 역행렬: 곱해서 단위행렬이 나오는 행렬/ 행렬의 나눗셈을 위해 구해서 곱해지는 행렬(정방행렬만 가능)
# - 특이행렬: 역행렬이 없는 행렬
# - 직교행렬: 행렬*행렬.T= 행렬.T*행렬 = I인 행렬 / 행렬 축의 정직교, 각축간의 내적이 0인 행렬
# - 정방행렬이면서 대칭행렬: 공분산행렬, 상관계수행렬, 거리행렬
# - 공분산: 두 수간의 관계 (한수-평균) * (다른수-평균)
# - 상관계수(표준화 -1 ~ 1): 공분산 / 표준편차의 곱

In [103]:
import numpy as np
F1 = np.array([[1,2],[3,4]]) # 2x2
F2 = np.array([[2,2],[2,2]]) # 2x2
print(F1)
print(F2)
print(F1 + F2) # 요소끼리 
print(F1 * F2)
print(F1 @ F2) # 행렬곱도 내적
# 1,2   2,2     6, 6     두 벡터의 사이각을 구해
# 3,4   2,2    14,14

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [104]:
# 방정식의 해
# 2 x1 + x2 -2 x3 = -3
# 3 x1 +     2 x3 = 5
#   x1 + x2 -  x3 = -2
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]])) # 열로 전치
print(b)
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌 / 연립방정식 해 풀기
# 2x + 1y -2z = -3
# 3x + 0y +1z = 5
# 1x + 1y -1z = -2
# 해: x=1, y=-1, z=2
print(x)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]
[[ 1.]
 [-1.]
 [ 2.]]


In [110]:
# 아래 세 개 다 값이 같음 (위 방정식 문제의 답)
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌 # Linear Algebra = 선형 대수
print(x)
print(np.dot(np.linalg.inv(A),b)) # 행렬곱98
print(np.linalg.inv(A)@b) # 왜 역행렬을 구해야 하는가? 행렬은 나눗셈이 없어서 역행렬 곱해서

[[ 1.]
 [-1.]
 [ 2.]]
[[ 1.]
 [-1.]
 [ 2.]]
[[ 1.]
 [-1.]
 [ 2.]]


In [111]:
a = np.array([0,1,0]) # y축
b = np.array([1,0,0]) # x축
res = np.dot(a,b) # 내적 사이각 = 직각
print(res)

0


In [112]:
#################################################################################################################
# Norm
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b)) # cos(theta)
# rad = np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b)) | cos(세타)값 = 내적 사이각/벡터A크기*벡터B크기
print("cos theta", rad)
print(np.arccos(rad)) # theta 값을 구함
print(np.degrees(np.arccos(rad))) # 사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [143]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [114]:
# 문제: 방정식의 해 구하기
#  x +  y  + z = 6
# 2y +      5z = -4
# 2x + 5y  - z = 27
A = np.array([[1,1,1],[2,0,5],[2,5,-1]])
print(A)
b = np.transpose(np.array([[6,-4,27]])) # 열로 전치
print(b)
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌
print(x)

# 답: 13, -1, -6


[[ 1  1  1]
 [ 2  0  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]
[[13.]
 [-1.]
 [-6.]]


In [118]:
arr2d = np.array([ [[1,2], [4,5]], [[7,8], [10,11]] ])
print(arr2d.ndim) # 3차원


3
